export const dayIndicators = {
  dayGainers: {
    canonicalName: 'DAY_GAINERS',
    quotes: [
      {
        language: 'US',
        region: 'EN-US',
        quoteType: 'EQUITY',
        quoteSourceName: 'Delayed Quote',
        triggerable: false,
        firstTradeDateMilliseconds: 1191245400000,
        priceHint: 2,
        exchange: 'NYQ',
        market: 'us_market',
        fullExchangeName: 'NYSE',
        marketState: 'REGULAR',
        sourceInterval: 15,
        exchangeDataDelayedBy: 0,
        exchangeTimezoneName: 'America/New_York',
        exchangeTimezoneShortName: 'EDT',
        gmtOffSetMilliseconds: -14400000,
        esgPopulated: false,
        tradeable: true,
        symbol: 'TDC',
        regularMarketPrice: 50.4,
        changeInPercent: 26.37,
        prevClose: 39.88,
      },
      {
        language: 'US',
        region: 'EN-US',
        quoteType: 'EQUITY',
        quoteSourceName: 'Delayed Quote',
        triggerable: false,
        firstTradeDateMilliseconds: 1611844200000,
        priceHint: 2,
        exchange: 'NMS',
        market: 'us_market',
        fullExchangeName: 'NasdaqGS',
        marketState: 'REGULAR',
        sourceInterval: 15,
        exchangeDataDelayedBy: 0,
        exchangeTimezoneName: 'America/New_York',
        exchangeTimezoneShortName: 'EDT',
        gmtOffSetMilliseconds: -14400000,
        esgPopulated: false,
        tradeable: true,
        symbol: 'XM',
        regularMarketPrice: 41.19,
        changeInPercent: 21.79,
        prevClose: 33.82,
      },
      {
        language: 'US',
        region: 'EN-US',
        quoteType: 'EQUITY',
        quoteSourceName: 'Delayed Quote',
        triggerable: false,
        firstTradeDateMilliseconds: 1528723800000,
        priceHint: 2,
        exchange: 'NMS',
        market: 'us_market',
        fullExchangeName: 'NasdaqGS',
        marketState: 'REGULAR',
        sourceInterval: 15,
        exchangeDataDelayedBy: 0,
        exchangeTimezoneName: 'America/New_York',
        exchangeTimezoneShortName: 'EDT',
        gmtOffSetMilliseconds: -14400000,
        esgPopulated: false,
        tradeable: true,
        symbol: 'NKLA',
        regularMarketPrice: 11.64,
        changeInPercent: 13.12,
        prevClose: 10.29,
      },
      {
        language: 'US',
        region: 'EN-US',
        quoteType: 'EQUITY',
        quoteSourceName: 'Delayed Quote',
        triggerable: false,
        firstTradeDateMilliseconds: 322151400000,
        priceHint: 2,
        exchange: 'NYQ',
        market: 'us_market',
        fullExchangeName: 'NYSE',
        marketState: 'REGULAR',
        sourceInterval: 15,
        exchangeDataDelayedBy: 0,
        exchangeTimezoneName: 'America/New_York',
        exchangeTimezoneShortName: 'EDT',
        gmtOffSetMilliseconds: -14400000,
        esgPopulated: false,
        tradeable: true,
        symbol: 'EFX',
        regularMarketPrice: 223.89,
        changeInPercent: 16.23,
        prevClose: 10.97,
      },
      {
        language: 'US',
        region: 'EN-US',
        quoteType: 'EQUITY',
        quoteSourceName: 'Delayed Quote',
        triggerable: false,
        firstTradeDateMilliseconds: 1605796200000,
        priceHint: 2,
        exchange: 'NYQ',
        market: 'us_market',
        fullExchangeName: 'NYSE',
        marketState: 'REGULAR',
        sourceInterval: 15,
        exchangeDataDelayedBy: 0,
        exchangeTimezoneName: 'America/New_York',
        exchangeTimezoneShortName: 'EDT',
        gmtOffSetMilliseconds: -14400000,
        esgPopulated: false,
        tradeable: true,
        symbol: 'YSG',
        regularMarketPrice: 11.45,
        changeInPercent: 4.38,
        prevClose: 10.97,
      },
      {
        language: 'US',
        region: 'EN-US',
        quoteType: 'EQUITY',
        quoteSourceName: 'Delayed Quote',
        triggerable: false,
        firstTradeDateMilliseconds: 1286458200000,
        priceHint: 2,
        exchange: 'NYQ',
        market: 'us_market',
        fullExchangeName: 'NYSE',
        marketState: 'REGULAR',
        sourceInterval: 15,
        exchangeDataDelayedBy: 0,
        exchangeTimezoneName: 'America/New_York',
        exchangeTimezoneShortName: 'EDT',
        gmtOffSetMilliseconds: -14400000,
        esgPopulated: false,
        tradeable: true,
        symbol: 'DQ',
        regularMarketPrice: 85.6,
        changeInPercent: 14.3,
        prevClose: 74.89,
      },
    ],
  },
  dayLosers: {
    canonicalName: 'DAY_LOSERS',
    quotes: [
      {
        language: 'US',
        region: 'EN-US',
        quoteType: 'EQUITY',
        quoteSourceName: 'Delayed Quote',
        triggerable: false,
        firstTradeDateMilliseconds: 354378600000,
        priceHint: 2,
        exchange: 'NMS',
        market: 'us_market',
        fullExchangeName: 'NasdaqGS',
        marketState: 'REGULAR',
        sourceInterval: 15,
        exchangeDataDelayedBy: 0,
        exchangeTimezoneName: 'America/New_York',
        exchangeTimezoneShortName: 'EDT',
        gmtOffSetMilliseconds: -14400000,
        esgPopulated: false,
        tradeable: true,
        symbol: 'SEIC',
        regularMarketPrice: 56.08,
        changeInPercent: -11,
        prevClose: 63.01,
      },
      {
        language: 'US',
        region: 'EN-US',
        quoteType: 'EQUITY',
        quoteSourceName: 'Delayed Quote',
        triggerable: false,
        firstTradeDateMilliseconds: 1462800600000,
        priceHint: 2,
        exchange: 'PNK',
        market: 'us_market',
        fullExchangeName: 'Other OTC',
        marketState: 'REGULAR',
        sourceInterval: 15,
        exchangeDataDelayedBy: 0,
        exchangeTimezoneName: 'America/New_York',
        exchangeTimezoneShortName: 'EDT',
        gmtOffSetMilliseconds: -14400000,
        esgPopulated: false,
        tradeable: true,
        symbol: 'EOLS',
        regularMarketPrice: 9.51,
        changeInPercent: -18.86,
        prevClose: 11.72,
      },
      {
        language: 'US',
        region: 'EN-US',
        quoteType: 'EQUITY',
        quoteSourceName: 'Delayed Quote',
        triggerable: false,
        firstTradeDateMilliseconds: 912781800000,
        priceHint: 2,
        exchange: 'NMS',
        market: 'us_market',
        fullExchangeName: 'NasdaqGS',
        marketState: 'REGULAR',
        sourceInterval: 15,
        exchangeDataDelayedBy: 0,
        exchangeTimezoneName: 'America/New_York',
        exchangeTimezoneShortName: 'EDT',
        gmtOffSetMilliseconds: -14400000,
        esgPopulated: false,
        tradeable: true,
        symbol: 'SNBR',
        regularMarketPrice: 110.13,
        changeInPercent: -11.85,
        prevClose: 124.93,
      },
      {
        language: 'US',
        region: 'EN-US',
        quoteType: 'EQUITY',
        quoteSourceName: 'Delayed Quote',
        triggerable: false,
        firstTradeDateMilliseconds: 1234535400000,
        priceHint: 2,
        exchange: 'PNK',
        market: 'us_market',
        fullExchangeName: 'Other OTC',
        marketState: 'REGULAR',
        sourceInterval: 15,
        exchangeDataDelayedBy: 0,
        exchangeTimezoneName: 'America/New_York',
        exchangeTimezoneShortName: 'EDT',
        gmtOffSetMilliseconds: -14400000,
        esgPopulated: false,
        tradeable: true,
        symbol: 'TIPT',
        regularMarketPrice: 12.36,
        changeInPercent: -13.08,
        prevClose: 14.22,
      },
      {
        language: 'US',
        region: 'EN-US',
        quoteType: 'EQUITY',
        quoteSourceName: 'Delayed Quote',
        triggerable: false,
        firstTradeDateMilliseconds: 1022160600000,
        priceHint: 2,
        exchange: 'PNK',
        market: 'us_market',
        fullExchangeName: 'Other OTC',
        marketState: 'REGULAR',
        sourceInterval: 15,
        exchangeDataDelayedBy: 0,
        exchangeTimezoneName: 'America/New_York',
        exchangeTimezoneShortName: 'EDT',
        gmtOffSetMilliseconds: -14400000,
        esgPopulated: false,
        tradeable: true,
        symbol: 'ALDX',
        regularMarketPrice: 10.44,
        changeInPercent: -11.82,
        prevClose: 11.84,
      },
      {
        language: 'US',
        region: 'EN-US',
        quoteType: 'EQUITY',
        quoteSourceName: 'Delayed Quote',
        triggerable: false,
        firstTradeDateMilliseconds: 1257345000000,
        priceHint: 2,
        exchange: 'PNK',
        market: 'us_market',
        fullExchangeName: 'Other OTC',
        marketState: 'REGULAR',
        sourceInterval: 15,
        exchangeDataDelayedBy: 0,
        exchangeTimezoneName: 'America/New_York',
        exchangeTimezoneShortName: 'EDT',
        gmtOffSetMilliseconds: -14400000,
        esgPopulated: false,
        tradeable: true,
        symbol: 'RIOT',
        regularMarketPrice: 36.49,
        changeInPercent: -11.67,
        prevClose: 41.31,
      },
    ],
  },
  activeMovers: {
    canonicalName: 'MOST_ACTIVES',
    quotes: [
      {
        language: 'US',
        region: 'EN-US',
        quoteType: 'EQUITY',
        quoteSourceName: 'Delayed Quote',
        triggerable: false,
        marketState: 'REGULAR',
        sourceInterval: 15,
        exchangeDataDelayedBy: 0,
        exchangeTimezoneName: 'America/New_York',
        exchangeTimezoneShortName: 'EDT',
        gmtOffSetMilliseconds: -14400000,
        esgPopulated: false,
        tradeable: true,
        firstTradeDateMilliseconds: 1587994200000,
        priceHint: 2,
        exchange: 'NYQ',
        market: 'us_market',
        fullExchangeName: 'NYSE',
        symbol: 'OCGN',
        regularMarketPrice: 9.29,
        changeInPercent: 42.92,
        prevClose: 6.5,
      },
      {
        language: 'US',
        region: 'EN-US',
        quoteType: 'EQUITY',
        quoteSourceName: 'Delayed Quote',
        triggerable: false,
        marketState: 'REGULAR',
        sourceInterval: 15,
        exchangeDataDelayedBy: 0,
        exchangeTimezoneName: 'America/New_York',
        exchangeTimezoneShortName: 'EDT',
        gmtOffSetMilliseconds: -14400000,
        esgPopulated: false,
        tradeable: true,
        firstTradeDateMilliseconds: 438273000000,
        priceHint: 2,
        exchange: 'NYQ',
        market: 'us_market',
        fullExchangeName: 'NYSE',
        symbol: 'SNDL',
        regularMarketPrice: 0.83,
        changeInPercent: 0.83,
        prevClose: 0.87,
      },
      {
        language: 'US',
        region: 'EN-US',
        quoteType: 'EQUITY',
        quoteSourceName: 'Delayed Quote',
        triggerable: false,
        marketState: 'REGULAR',
        sourceInterval: 15,
        exchangeDataDelayedBy: 0,
        exchangeTimezoneName: 'America/New_York',
        exchangeTimezoneShortName: 'EDT',
        gmtOffSetMilliseconds: -14400000,
        esgPopulated: false,
        tradeable: true,
        firstTradeDateMilliseconds: 1536759000000,
        priceHint: 2,
        exchange: 'NYQ',
        market: 'us_market',
        fullExchangeName: 'NYSE',
        symbol: 'UVXY',
        regularMarketPrice: 4.93,
        changeInPercent: 9.31,
        prevClose: 4.51,
      },
      {
        language: 'US',
        region: 'EN-US',
        quoteType: 'EQUITY',
        quoteSourceName: 'Delayed Quote',
        triggerable: false,
        marketState: 'REGULAR',
        sourceInterval: 15,
        exchangeDataDelayedBy: 0,
        exchangeTimezoneName: 'America/New_York',
        exchangeTimezoneShortName: 'EDT',
        gmtOffSetMilliseconds: -14400000,
        esgPopulated: false,
        tradeable: true,
        firstTradeDateMilliseconds: 1528723800000,
        priceHint: 2,
        exchange: 'NMS',
        market: 'us_market',
        fullExchangeName: 'NasdaqGS',
        symbol: 'NKLA',
        regularMarketPrice: 11.77,
        changeInPercent: 14.38,
        prevClose: 10.29,
      },
      {
        language: 'US',
        region: 'EN-US',
        quoteType: 'EQUITY',
        quoteSourceName: 'Delayed Quote',
        triggerable: false,
        marketState: 'REGULAR',
        sourceInterval: 15,
        exchangeDataDelayedBy: 0,
        exchangeTimezoneName: 'America/New_York',
        exchangeTimezoneShortName: 'EDT',
        gmtOffSetMilliseconds: -14400000,
        esgPopulated: false,
        tradeable: true,
        firstTradeDateMilliseconds: 1127827800000,
        priceHint: 2,
        exchange: 'NMS',
        market: 'us_market',
        fullExchangeName: 'NasdaqGS',
        symbol: 'AAL',
        regularMarketPrice: 20.07,
        changeInPercent: -4.47,
        prevClose: 21.01,
      },
      {
        language: 'US',
        region: 'EN-US',
        quoteType: 'EQUITY',
        quoteSourceName: 'Delayed Quote',
        triggerable: false,
        marketState: 'REGULAR',
        sourceInterval: 15,
        exchangeDataDelayedBy: 0,
        exchangeTimezoneName: 'America/New_York',
        exchangeTimezoneShortName: 'EDT',
        gmtOffSetMilliseconds: -14400000,
        esgPopulated: false,
        tradeable: true,
        firstTradeDateMilliseconds: 345479400000,
        priceHint: 2,
        exchange: 'NMS',
        market: 'us_market',
        fullExchangeName: 'NasdaqGS',
        symbol: 'AAPL',
        regularMarketPrice: 131.94,
        changeInPercent: -1.17,
        prevClose: 131.94,
      },
    ],
  },
};

export const topTrendingTickers = {
  NYSE: [
    {
      language: 'en-US',
      region: 'US',
      quoteType: 'CRYPTOCURRENCY',
      triggerable: true,
      quoteSourceName: 'CryptoCurrency',
      regularMarketPrice: 0.6736317,
      regularMarketTime: 1620213183,
      regularMarketChange: 0.19350499,
      esgPopulated: false,
      regularMarketChangePercent: 40.30289,
      regularMarketPreviousClose: 0.54994214,
      fullExchangeName: 'CCC',
      priceHint: 4,
      sourceInterval: 15,
      exchangeTimezoneName: 'Africa/Abidjan',
      exchangeTimezoneShortName: 'GMT',
      gmtOffSetMilliseconds: 0,
      tradeable: false,
      shortName: 'Dogecoin USD',
      exchange: 'CCC',
      market: 'ccc_market',
      exchangeDataDelayedBy: 0,
      marketState: 'REGULAR',
      symbol: 'DOGE-USD',
    },
    {
      language: 'en-US',
      region: 'US',
      quoteType: 'EQUITY',
      triggerable: true,
      quoteSourceName: 'Delayed Quote',
      regularMarketPrice: 88.69,
      regularMarketTime: 1620158402,
      regularMarketChange: -2.459999,
      esgPopulated: false,
      regularMarketChangePercent: -2.698847,
      regularMarketPreviousClose: 91.15,
      fullExchangeName: 'NasdaqGS',
      longName: 'Activision Blizzard, Inc.',
      priceHint: 2,
      sourceInterval: 15,
      exchangeTimezoneName: 'America/New_York',
      exchangeTimezoneShortName: 'EDT',
      gmtOffSetMilliseconds: -14400000,
      tradeable: false,
      shortName: 'Activision Blizzard, Inc',
      exchange: 'NMS',
      market: 'us_market',
      exchangeDataDelayedBy: 0,
      marketState: 'PRE',
      symbol: 'ATVI',
    },
    {
      language: 'en-US',
      region: 'US',
      quoteType: 'EQUITY',
      triggerable: true,
      quoteSourceName: 'Delayed Quote',
      regularMarketPrice: 2.14,
      regularMarketTime: 1620158402,
      regularMarketChange: 0.9000001,
      esgPopulated: false,
      regularMarketChangePercent: 72.58065,
      regularMarketPreviousClose: 1.24,
      fullExchangeName: 'NasdaqGS',
      longName: 'Cocrystal Pharma, Inc.',
      priceHint: 4,
      sourceInterval: 15,
      exchangeTimezoneName: 'America/New_York',
      exchangeTimezoneShortName: 'EDT',
      gmtOffSetMilliseconds: -14400000,
      tradeable: false,
      shortName: 'Cocrystal Pharma, Inc.',
      exchange: 'NMS',
      market: 'us_market',
      exchangeDataDelayedBy: 0,
      marketState: 'PRE',
      symbol: 'COCP',
    },
    {
      language: 'en-US',
      region: 'US',
      quoteType: 'EQUITY',
      triggerable: true,
      quoteSourceName: 'Delayed Quote',
      regularMarketPrice: 4.88,
      regularMarketTime: 1620158402,
      regularMarketChange: 1.69,
      esgPopulated: false,
      regularMarketChangePercent: 52.978058,
      regularMarketPreviousClose: 3.19,
      fullExchangeName: 'NasdaqGS',
      longName: 'BioLineRx Ltd.',
      priceHint: 4,
      sourceInterval: 15,
      exchangeTimezoneName: 'America/New_York',
      exchangeTimezoneShortName: 'EDT',
      gmtOffSetMilliseconds: -14400000,
      tradeable: false,
      shortName: 'BioLineRx Ltd.',
      exchange: 'NMS',
      market: 'us_market',
      exchangeDataDelayedBy: 0,
      marketState: 'PRE',
      symbol: 'BLRX',
    },
    {
      language: 'en-US',
      region: 'US',
      quoteType: 'EQUITY',
      triggerable: false,
      regularMarketPrice: 40.9,
      regularMarketTime: 1620212367,
      regularMarketChange: 14.760002,
      esgPopulated: false,
      regularMarketChangePercent: 56.465195,
      regularMarketPreviousClose: 26.14,
      fullExchangeName: 'Oslo',
      longName: 'Norwegian Air Shuttle ASA',
      priceHint: 2,
      sourceInterval: 15,
      exchangeTimezoneName: 'Europe/Oslo',
      exchangeTimezoneShortName: 'CEST',
      gmtOffSetMilliseconds: 7200000,
      tradeable: false,
      shortName: 'NORWEGIAN AIR SHUT',
      exchange: 'OSL',
      market: 'no_market',
      exchangeDataDelayedBy: 0,
      marketState: 'REGULAR',
      symbol: 'NAS.OL',
    },
    {
      language: 'en-US',
      region: 'US',
      quoteType: 'EQUITY',
      triggerable: true,
      quoteSourceName: 'Delayed Quote',
      regularMarketPrice: 1.29,
      regularMarketTime: 1620158400,
      regularMarketChange: -0.060000062,
      esgPopulated: false,
      regularMarketChangePercent: -4.444449,
      regularMarketPreviousClose: 1.35,
      fullExchangeName: 'NYSE American',
      longName: 'iBio, Inc.',
      priceHint: 4,
      sourceInterval: 15,
      exchangeTimezoneName: 'America/New_York',
      exchangeTimezoneShortName: 'EDT',
      gmtOffSetMilliseconds: -14400000,
      tradeable: false,
      shortName: 'iBio, Inc.',
      exchange: 'ASE',
      market: 'us_market',
      exchangeDataDelayedBy: 0,
      marketState: 'PRE',
      symbol: 'IBIO',
    },
    {
      language: 'en-US',
      region: 'US',
      quoteType: 'CRYPTOCURRENCY',
      triggerable: true,
      quoteSourceName: 'CryptoCurrency',
      regularMarketPrice: 49.747906,
      regularMarketTime: 1620213191,
      regularMarketChange: 14.304691,
      esgPopulated: false,
      regularMarketChangePercent: 40.35946,
      regularMarketPreviousClose: 40.57426,
      fullExchangeName: 'CCC',
      sourceInterval: 15,
      exchangeTimezoneName: 'Africa/Abidjan',
      exchangeTimezoneShortName: 'GMT',
      gmtOffSetMilliseconds: 0,
      tradeable: false,
      shortName: 'Dogecoin INR',
      exchange: 'CCC',
      market: 'ccc_market',
      exchangeDataDelayedBy: 0,
      marketState: 'REGULAR',
      symbol: 'DOGE-INR',
    },
    {
      language: 'en-US',
      region: 'US',
      quoteType: 'EQUITY',
      triggerable: true,
      quoteSourceName: 'Delayed Quote',
      regularMarketPrice: 127.85,
      regularMarketTime: 1620158403,
      regularMarketChange: -4.689995,
      esgPopulated: false,
      regularMarketChangePercent: -3.5385509,
      regularMarketPreviousClose: 132.54,
      fullExchangeName: 'NasdaqGS',
      longName: 'Apple Inc.',
      priceHint: 2,
      sourceInterval: 15,
      exchangeTimezoneName: 'America/New_York',
      exchangeTimezoneShortName: 'EDT',
      gmtOffSetMilliseconds: -14400000,
      tradeable: false,
      shortName: 'Apple Inc.',
      exchange: 'NMS',
      market: 'us_market',
      exchangeDataDelayedBy: 0,
      marketState: 'PRE',
      symbol: 'AAPL',
    },
    {
      language: 'en-US',
      region: 'US',
      quoteType: 'EQUITY',
      triggerable: true,
      quoteSourceName: 'Delayed Quote',
      regularMarketPrice: 3.71,
      regularMarketTime: 1620158401,
      regularMarketChange: -0.14999986,
      esgPopulated: false,
      regularMarketChangePercent: -3.8860068,
      regularMarketPreviousClose: 3.86,
      fullExchangeName: 'NasdaqGS',
      longName: 'Athenex, Inc.',
      priceHint: 4,
      sourceInterval: 15,
      exchangeTimezoneName: 'America/New_York',
      exchangeTimezoneShortName: 'EDT',
      gmtOffSetMilliseconds: -14400000,
      tradeable: false,
      shortName: 'Athenex, Inc.',
      exchange: 'NMS',
      market: 'us_market',
      exchangeDataDelayedBy: 0,
      marketState: 'PRE',
      symbol: 'ATNX',
    },
    {
      language: 'en-US',
      region: 'US',
      quoteType: 'CRYPTOCURRENCY',
      triggerable: true,
      quoteSourceName: 'CryptoCurrency',
      regularMarketPrice: 76.88957,
      regularMarketTime: 1620213185,
      regularMarketChange: 22.33657,
      esgPopulated: false,
      regularMarketChangePercent: 40.944714,
      regularMarketPreviousClose: 69.19614,
      fullExchangeName: 'CCC',
      sourceInterval: 15,
      exchangeTimezoneName: 'Africa/Abidjan',
      exchangeTimezoneShortName: 'GMT',
      gmtOffSetMilliseconds: 0,
      tradeable: false,
      shortName: 'EthereumClassic USD',
      exchange: 'CCC',
      market: 'ccc_market',
      exchangeDataDelayedBy: 0,
      marketState: 'REGULAR',
      symbol: 'ETC-USD',
    },
    {
      language: 'en-US',
      region: 'US',
      quoteType: 'EQUITY',
      triggerable: true,
      quoteSourceName: 'Delayed Quote',
      regularMarketPrice: 1.07,
      regularMarketTime: 1620158402,
      regularMarketChange: 0.30610007,
      esgPopulated: false,
      regularMarketChangePercent: 40.0707,
      regularMarketPreviousClose: 0.7639,
      fullExchangeName: 'NasdaqGS',
      longName: 'Adamis Pharmaceuticals Corporation',
      priceHint: 4,
      sourceInterval: 15,
      exchangeTimezoneName: 'America/New_York',
      exchangeTimezoneShortName: 'EDT',
      gmtOffSetMilliseconds: -14400000,
      tradeable: false,
      shortName: 'Adamis Pharmaceuticals Corporat',
      exchange: 'NMS',
      market: 'us_market',
      exchangeDataDelayedBy: 0,
      marketState: 'PRE',
      symbol: 'ADMP',
    },
    {
      language: 'en-US',
      region: 'US',
      quoteType: 'EQUITY',
      triggerable: true,
      quoteSourceName: 'Delayed Quote',
      regularMarketPrice: 10.43,
      regularMarketTime: 1620158402,
      regularMarketChange: 0.020000458,
      esgPopulated: false,
      regularMarketChangePercent: 0.19212735,
      regularMarketPreviousClose: 10.41,
      fullExchangeName: 'NYSE',
      longName: 'Social Capital Hedosophia Holdings Corp. VI',
      priceHint: 2,
      sourceInterval: 15,
      exchangeTimezoneName: 'America/New_York',
      exchangeTimezoneShortName: 'EDT',
      gmtOffSetMilliseconds: -14400000,
      tradeable: false,
      shortName: 'Social Capital Hedosophia Holdi',
      exchange: 'NYQ',
      market: 'us_market',
      exchangeDataDelayedBy: 0,
      marketState: 'PRE',
      symbol: 'IPOF',
    },
    {
      language: 'en-US',
      region: 'US',
      quoteType: 'EQUITY',
      triggerable: true,
      quoteSourceName: 'Delayed Quote',
      regularMarketPrice: 56.19,
      regularMarketTime: 1620158403,
      regularMarketChange: -0.8900032,
      esgPopulated: false,
      regularMarketChangePercent: -1.5592207,
      regularMarketPreviousClose: 57.08,
      fullExchangeName: 'NasdaqGS',
      longName: 'Lyft, Inc.',
      priceHint: 2,
      sourceInterval: 15,
      exchangeTimezoneName: 'America/New_York',
      exchangeTimezoneShortName: 'EDT',
      gmtOffSetMilliseconds: -14400000,
      tradeable: false,
      shortName: 'Lyft, Inc.',
      exchange: 'NMS',
      market: 'us_market',
      exchangeDataDelayedBy: 0,
      marketState: 'PRE',
      symbol: 'LYFT',
    },
    {
      language: 'en-US',
      region: 'US',
      quoteType: 'EQUITY',
      triggerable: true,
      quoteSourceName: 'Delayed Quote',
      regularMarketPrice: 21.64,
      regularMarketTime: 1620158402,
      regularMarketChange: -0.65999985,
      esgPopulated: false,
      regularMarketChangePercent: -2.9596407,
      regularMarketPreviousClose: 22.3,
      fullExchangeName: 'NYSE',
      longName: 'Palantir Technologies Inc.',
      priceHint: 2,
      sourceInterval: 15,
      exchangeTimezoneName: 'America/New_York',
      exchangeTimezoneShortName: 'EDT',
      gmtOffSetMilliseconds: -14400000,
      tradeable: false,
      shortName: 'Palantir Technologies Inc.',
      exchange: 'NYQ',
      market: 'us_market',
      exchangeDataDelayedBy: 0,
      marketState: 'PRE',
      symbol: 'PLTR',
    },
    {
      language: 'en-US',
      region: 'US',
      quoteType: 'CRYPTOCURRENCY',
      triggerable: true,
      quoteSourceName: 'CryptoCurrency',
      regularMarketPrice: 0.8268425,
      regularMarketTime: 1620213191,
      regularMarketChange: 0.23424882,
      esgPopulated: false,
      regularMarketChangePercent: 39.52942,
      regularMarketPreviousClose: 0.67662126,
      fullExchangeName: 'CCC',
      priceHint: 4,
      sourceInterval: 15,
      exchangeTimezoneName: 'Africa/Abidjan',
      exchangeTimezoneShortName: 'GMT',
      gmtOffSetMilliseconds: 0,
      tradeable: false,
      shortName: 'Dogecoin CAD',
      exchange: 'CCC',
      market: 'ccc_market',
      exchangeDataDelayedBy: 0,
      marketState: 'REGULAR',
      symbol: 'DOGE-CAD',
    },
    {
      language: 'en-US',
      region: 'US',
      quoteType: 'EQUITY',
      triggerable: true,
      quoteSourceName: 'Delayed Quote',
      regularMarketPrice: 16.96,
      regularMarketTime: 1620158402,
      regularMarketChange: 0.43999863,
      esgPopulated: false,
      regularMarketChangePercent: 2.6634297,
      regularMarketPreviousClose: 16.52,
      fullExchangeName: 'NYSE',
      longName: 'Skillz Inc.',
      priceHint: 2,
      sourceInterval: 15,
      exchangeTimezoneName: 'America/New_York',
      exchangeTimezoneShortName: 'EDT',
      gmtOffSetMilliseconds: -14400000,
      tradeable: false,
      shortName: 'Skillz Inc.',
      exchange: 'NYQ',
      market: 'us_market',
      exchangeDataDelayedBy: 0,
      marketState: 'PRE',
      symbol: 'SKLZ',
    },
    {
      language: 'en-US',
      region: 'US',
      quoteType: 'EQUITY',
      triggerable: true,
      quoteSourceName: 'Delayed Quote',
      regularMarketPrice: 20.36,
      regularMarketTime: 1620158402,
      regularMarketChange: 2.1500015,
      esgPopulated: false,
      regularMarketChangePercent: 11.806708,
      regularMarketPreviousClose: 18.21,
      fullExchangeName: 'NYSE',
      longName: 'Cleveland-Cliffs Inc.',
      priceHint: 2,
      sourceInterval: 15,
      exchangeTimezoneName: 'America/New_York',
      exchangeTimezoneShortName: 'EDT',
      gmtOffSetMilliseconds: -14400000,
      tradeable: false,
      shortName: 'Cleveland-Cliffs Inc.',
      exchange: 'NYQ',
      market: 'us_market',
      exchangeDataDelayedBy: 0,
      marketState: 'PRE',
      symbol: 'CLF',
    },
    {
      language: 'en-US',
      region: 'US',
      quoteType: 'EQUITY',
      triggerable: true,
      quoteSourceName: 'Delayed Quote',
      regularMarketPrice: 76.39,
      regularMarketTime: 1620158402,
      regularMarketChange: -2.7200012,
      esgPopulated: false,
      regularMarketChangePercent: -3.4382522,
      regularMarketPreviousClose: 79.11,
      fullExchangeName: 'NYSE',
      longName: 'Alteryx, Inc.',
      priceHint: 2,
      sourceInterval: 15,
      exchangeTimezoneName: 'America/New_York',
      exchangeTimezoneShortName: 'EDT',
      gmtOffSetMilliseconds: -14400000,
      tradeable: false,
      shortName: 'Alteryx, Inc.',
      exchange: 'NYQ',
      market: 'us_market',
      exchangeDataDelayedBy: 0,
      marketState: 'PRE',
      symbol: 'AYX',
    },
    {
      language: 'en-US',
      region: 'US',
      quoteType: 'EQUITY',
      triggerable: true,
      quoteSourceName: 'Delayed Quote',
      regularMarketPrice: 26.99,
      regularMarketTime: 1620158402,
      regularMarketChange: -4.25,
      esgPopulated: false,
      regularMarketChangePercent: -13.604353,
      regularMarketPreviousClose: 31.24,
      fullExchangeName: 'NYSE',
      longName: 'Jumia Technologies AG',
      priceHint: 2,
      sourceInterval: 15,
      exchangeTimezoneName: 'America/New_York',
      exchangeTimezoneShortName: 'EDT',
      gmtOffSetMilliseconds: -14400000,
      tradeable: false,
      shortName: 'Jumia Technologies AG',
      exchange: 'NYQ',
      market: 'us_market',
      exchangeDataDelayedBy: 0,
      marketState: 'PRE',
      symbol: 'JMIA',
    },
    {
      language: 'en-US',
      region: 'US',
      quoteType: 'EQUITY',
      triggerable: true,
      quoteSourceName: 'Delayed Quote',
      regularMarketPrice: 2.61,
      regularMarketTime: 1620158402,
      regularMarketChange: -0.22000003,
      esgPopulated: false,
      regularMarketChangePercent: -7.7738533,
      regularMarketPreviousClose: 2.83,
      fullExchangeName: 'NasdaqGS',
      longName: 'Ideanomics, Inc.',
      priceHint: 4,
      sourceInterval: 15,
      exchangeTimezoneName: 'America/New_York',
      exchangeTimezoneShortName: 'EDT',
      gmtOffSetMilliseconds: -14400000,
      tradeable: false,
      shortName: 'Ideanomics, Inc.',
      exchange: 'NMS',
      market: 'us_market',
      exchangeDataDelayedBy: 0,
      marketState: 'PRE',
      symbol: 'IDEX',
    },
  ],
  LSE: [
    {
      language: 'en-US',
      region: 'US',
      quoteType: 'CRYPTOCURRENCY',
      triggerable: true,
      quoteSourceName: 'CryptoCurrency',
      regularMarketChange: 0.12524661,
      market: 'ccc_market',
      regularMarketChangePercent: 35.69618,
      regularMarketPreviousClose: 0.3959979,
      fullExchangeName: 'CCC',
      marketState: 'REGULAR',
      shortName: 'Dogecoin GBP',
      sourceInterval: 15,
      exchangeTimezoneName: 'Africa/Abidjan',
      exchangeTimezoneShortName: 'GMT',
      gmtOffSetMilliseconds: 0,
      exchangeDataDelayedBy: 0,
      exchange: 'CCC',
      esgPopulated: false,
      tradeable: false,
      regularMarketPrice: 0.47611508,
      regularMarketTime: 1620214869,
      priceHint: 4,
      symbol: 'DOGE-GBP',
    },
    {
      language: 'en-US',
      region: 'US',
      quoteType: 'EQUITY',
      triggerable: true,
      quoteSourceName: 'Delayed Quote',
      regularMarketChange: -4.689995,
      market: 'us_market',
      regularMarketChangePercent: -3.5385509,
      regularMarketPreviousClose: 132.54,
      fullExchangeName: 'NasdaqGS',
      longName: 'Apple Inc.',
      marketState: 'PRE',
      shortName: 'Apple Inc.',
      sourceInterval: 15,
      exchangeTimezoneName: 'America/New_York',
      exchangeTimezoneShortName: 'EDT',
      gmtOffSetMilliseconds: -14400000,
      exchangeDataDelayedBy: 0,
      exchange: 'NMS',
      esgPopulated: false,
      tradeable: false,
      regularMarketPrice: 127.85,
      regularMarketTime: 1620158403,
      priceHint: 2,
      symbol: 'AAPL',
    },
    {
      language: 'en-US',
      region: 'US',
      quoteType: 'EQUITY',
      triggerable: true,
      quoteSourceName: 'Delayed Quote',
      regularMarketChange: -1.4700012,
      market: 'us_market',
      regularMarketChangePercent: -0.9062893,
      regularMarketPreviousClose: 162.2,
      fullExchangeName: 'NYSE',
      longName: 'GameStop Corp.',
      marketState: 'PRE',
      shortName: 'GameStop Corporation',
      sourceInterval: 15,
      exchangeTimezoneName: 'America/New_York',
      exchangeTimezoneShortName: 'EDT',
      gmtOffSetMilliseconds: -14400000,
      exchangeDataDelayedBy: 0,
      exchange: 'NYQ',
      esgPopulated: false,
      tradeable: false,
      regularMarketPrice: 160.73,
      regularMarketTime: 1620158402,
      priceHint: 2,
      symbol: 'GME',
    },
    {
      language: 'en-US',
      region: 'US',
      quoteType: 'EQUITY',
      triggerable: true,
      quoteSourceName: 'Delayed Quote',
      regularMarketChange: -0.3199997,
      market: 'us_market',
      regularMarketChangePercent: -3.2955685,
      regularMarketPreviousClose: 9.71,
      fullExchangeName: 'NYSE',
      longName: 'AMC Entertainment Holdings, Inc.',
      marketState: 'PRE',
      shortName: 'AMC Entertainment Holdings, Inc',
      sourceInterval: 15,
      exchangeTimezoneName: 'America/New_York',
      exchangeTimezoneShortName: 'EDT',
      gmtOffSetMilliseconds: -14400000,
      exchangeDataDelayedBy: 0,
      exchange: 'NYQ',
      esgPopulated: false,
      tradeable: false,
      regularMarketPrice: 9.39,
      regularMarketTime: 1620158402,
      priceHint: 2,
      symbol: 'AMC',
    },
    {
      language: 'en-US',
      region: 'US',
      quoteType: 'CRYPTOCURRENCY',
      triggerable: true,
      quoteSourceName: 'CryptoCurrency',
      regularMarketChange: 0.1765736,
      market: 'ccc_market',
      regularMarketChangePercent: 36.32379,
      regularMarketPreviousClose: 0.54994214,
      fullExchangeName: 'CCC',
      marketState: 'REGULAR',
      shortName: 'Dogecoin USD',
      sourceInterval: 15,
      exchangeTimezoneName: 'Africa/Abidjan',
      exchangeTimezoneShortName: 'GMT',
      gmtOffSetMilliseconds: 0,
      exchangeDataDelayedBy: 0,
      exchange: 'CCC',
      esgPopulated: false,
      tradeable: false,
      regularMarketPrice: 0.6626837,
      regularMarketTime: 1620214863,
      priceHint: 4,
      symbol: 'DOGE-USD',
    },
  ],
  SG: [
    {
      language: 'en-US',
      region: 'US',
      quoteType: 'EQUITY',
      triggerable: false,
      quoteSourceName: 'Delayed Quote',
      shortName: 'SIA',
      regularMarketPrice: 4.82,
      regularMarketTime: 1620206131,
      regularMarketChange: -0.14999962,
      exchange: 'SES',
      gmtOffSetMilliseconds: 28800000,
      market: 'sg_market',
      regularMarketChangePercent: -3.0181012,
      regularMarketPreviousClose: 4.97,
      fullExchangeName: 'SES',
      longName: 'Singapore Airlines Limited',
      marketState: 'POSTPOST',
      sourceInterval: 20,
      exchangeTimezoneName: 'Asia/Singapore',
      exchangeTimezoneShortName: 'SGT',
      esgPopulated: false,
      tradeable: false,
      priceHint: 4,
      exchangeDataDelayedBy: 0,
      symbol: 'C6L.SI',
    },
  ],
};
